"""add_text_to_speak_to_exercises

Revision ID: 3cdd7afec0ce
Revises: 8ad5fff97e92
Create Date: 2025-11-01 09:46:17.217395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cdd7afec0ce'
down_revision: Union[str, None] = '8ad5fff97e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
