"""dd_completed_exercises_count

Revision ID: 3dd9394ca212
Revises: c243cfa60f7d
Create Date: 2025-11-01 12:25:26.517578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dd9394ca212'
down_revision: Union[str, None] = 'c243cfa60f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise_question_options', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('exercise_question_options', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercise_question_options', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('exercise_question_options_question_id_fkey'), 'exercise_question_options', type_='foreignkey')
    op.create_foreign_key(None, 'exercise_question_options', 'exercise_questions', ['question_id'], ['id'])
    op.alter_column('exercise_questions', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercise_questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('exercise_questions_exercise_id_fkey'), 'exercise_questions', type_='foreignkey')
    op.create_foreign_key(None, 'exercise_questions', 'exercises', ['exercise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise_questions', type_='foreignkey')
    op.create_foreign_key(op.f('exercise_questions_exercise_id_fkey'), 'exercise_questions', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    op.alter_column('exercise_questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercise_questions', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'exercise_question_options', type_='foreignkey')
    op.create_foreign_key(op.f('exercise_question_options_question_id_fkey'), 'exercise_question_options', 'exercise_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.alter_column('exercise_question_options', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercise_question_options', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercise_question_options', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
