"""update table

Revision ID: 41931443617e
Revises: f86e6077e6b5
Create Date: 2025-10-06 08:39:51.165782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41931443617e'
down_revision: Union[str, None] = 'f86e6077e6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_constraint(op.f('fk_ai_logs_user_id'), 'ai_logs', type_='foreignkey')
    op.drop_constraint(op.f('fk_daily_goals_user_id'), 'daily_goals', type_='foreignkey')
    op.drop_constraint(op.f('fk_friends_user_id'), 'friends', type_='foreignkey')
    op.drop_constraint(op.f('fk_friends_friend_user_id'), 'friends', type_='foreignkey')
    op.drop_constraint(op.f('fk_leaderboard_user_id'), 'leaderboard', type_='foreignkey')
    op.drop_constraint(op.f('fk_lessons_unit_id'), 'lessons', type_='foreignkey')
    op.drop_constraint(op.f('fk_listening_exercises_lesson_id'), 'listening_exercises', type_='foreignkey')
    op.drop_constraint(op.f('fk_notifications_user_id'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('fk_question_options_question_id'), 'question_options', type_='foreignkey')
    op.drop_constraint(op.f('fk_questions_quiz_id'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_lesson_id'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_speaking_exercises_lesson_id'), 'speaking_exercises', type_='foreignkey')
    op.drop_constraint(op.f('fk_units_course_id'), 'units', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_badges_user_id'), 'user_badges', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_badges_badge_id'), 'user_badges', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_challenges_challenge_id'), 'user_challenges', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_challenges_user_id'), 'user_challenges', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_course_progress_course_id'), 'user_course_progress', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_course_progress_user_id'), 'user_course_progress', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_exp_log_user_id'), 'user_exp_log', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_lesson_progress_lesson_id'), 'user_lesson_progress', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_lesson_progress_user_id'), 'user_lesson_progress', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_question_attempts_question_id'), 'user_question_attempts', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_question_attempts_user_quiz_attempt_id'), 'user_question_attempts', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_question_errors_question_id'), 'user_question_errors', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_question_errors_user_id'), 'user_question_errors', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_quiz_attempts_user_id'), 'user_quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_quiz_attempts_quiz_id'), 'user_quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_unit_progress_unit_id'), 'user_unit_progress', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_unit_progress_user_id'), 'user_unit_progress', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_tier_id'), 'users', type_='foreignkey')
    op.drop_column('users', 'tier_id')
    op.drop_constraint(op.f('fk_writing_exercises_lesson_id'), 'writing_exercises', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_writing_exercises_lesson_id'), 'writing_exercises', 'lessons', ['lesson_id'], ['id'])
    op.add_column('users', sa.Column('tier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_users_tier_id'), 'users', 'tier', ['tier_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_unit_progress_user_id'), 'user_unit_progress', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_unit_progress_unit_id'), 'user_unit_progress', 'units', ['unit_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_quiz_attempts_quiz_id'), 'user_quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_quiz_attempts_user_id'), 'user_quiz_attempts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_question_errors_user_id'), 'user_question_errors', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_question_errors_question_id'), 'user_question_errors', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_question_attempts_user_quiz_attempt_id'), 'user_question_attempts', 'user_quiz_attempts', ['user_quiz_attempt_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_question_attempts_question_id'), 'user_question_attempts', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_lesson_progress_user_id'), 'user_lesson_progress', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_lesson_progress_lesson_id'), 'user_lesson_progress', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_exp_log_user_id'), 'user_exp_log', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_course_progress_user_id'), 'user_course_progress', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_course_progress_course_id'), 'user_course_progress', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_challenges_user_id'), 'user_challenges', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_challenges_challenge_id'), 'user_challenges', 'challenges', ['challenge_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_badges_badge_id'), 'user_badges', 'badges', ['badge_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_badges_user_id'), 'user_badges', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_units_course_id'), 'units', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(op.f('fk_speaking_exercises_lesson_id'), 'speaking_exercises', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(op.f('fk_quizzes_lesson_id'), 'quizzes', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(op.f('fk_questions_quiz_id'), 'questions', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(op.f('fk_question_options_question_id'), 'question_options', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(op.f('fk_notifications_user_id'), 'notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_listening_exercises_lesson_id'), 'listening_exercises', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(op.f('fk_lessons_unit_id'), 'lessons', 'units', ['unit_id'], ['id'])
    op.create_foreign_key(op.f('fk_leaderboard_user_id'), 'leaderboard', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_friends_friend_user_id'), 'friends', 'users', ['friend_user_id'], ['id'])
    op.create_foreign_key(op.f('fk_friends_user_id'), 'friends', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_daily_goals_user_id'), 'daily_goals', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_ai_logs_user_id'), 'ai_logs', 'users', ['user_id'], ['id'])
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
