"""completed_exercises_count

Revision ID: 512f7e1dc89c
Revises: 3dd9394ca212
Create Date: 2025-11-01 12:37:54.876365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512f7e1dc89c'
down_revision: Union[str, None] = '3dd9394ca212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server_default to avoid errors on existing rows
    op.add_column(
        'user_lesson_progress',
        sa.Column('completed_exercises_count', sa.Integer(), nullable=False, server_default='0')
    )
    # Remove server_default after adding column (optional, but cleaner)
    op.alter_column(
        'user_lesson_progress',
        'completed_exercises_count',
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_lesson_progress', 'completed_exercises_count')
    # ### end Alembic commands ###
