"""drop table challenge

Revision ID: 8ad5fff97e92
Revises: 1369c014ecdf
Create Date: 2025-11-01 03:13:04.766325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ad5fff97e92'
down_revision: Union[str, None] = '1369c014ecdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    table_names = set(inspector.get_table_names())
    
    # Drop user_challenges table if it exists
    if 'user_challenges' in table_names:
        # Drop foreign key constraints first (must drop before tables)
        constraints = {fk['name'] for fk in inspector.get_foreign_keys('user_challenges')}
        if 'user_challenges_challenge_id_fkey' in constraints:
            op.drop_constraint('user_challenges_challenge_id_fkey', 'user_challenges', type_='foreignkey')
        
        if 'user_challenges_user_id_fkey' in constraints:
            op.drop_constraint('user_challenges_user_id_fkey', 'user_challenges', type_='foreignkey')
        
        # Drop indexes if they exist
        indexes = {idx['name'] for idx in inspector.get_indexes('user_challenges')}
        if 'ix_user_challenges_challenge_id' in indexes:
            op.drop_index('ix_user_challenges_challenge_id', table_name='user_challenges')
        if 'ix_user_challenges_user_id' in indexes:
            op.drop_index('ix_user_challenges_user_id', table_name='user_challenges')
        
        # Drop table
        op.drop_table('user_challenges')
    
    # Drop challenges table if it exists
    if 'challenges' in table_names:
        op.drop_table('challenges')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_challenges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('progress_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('user_challenges_challenge_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_challenges_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_challenges_pkey'))
    )
    op.create_table('challenges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('exp_reward', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('challenges_pkey'))
    )
    # ### end Alembic commands ###
