"""Add entry test flow tables and user fields

Revision ID: add_entry_test_flow
Revises: add_picture_field_to_users
Create Date: 2024-01-15 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add_entry_test_flow'
down_revision: Union[str, None] = 'add_picture_field_to_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new fields to users table
    op.add_column('users', sa.Column('current_course_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('entry_test_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('has_completed_entry_test', sa.Boolean(), nullable=False, server_default='false'))
    
    # Add foreign key constraint for current_course_id
    op.create_foreign_key('fk_users_current_course_id', 'users', 'courses', ['current_course_id'], ['id'])
    
    # Create entry_tests table
    op.create_table('entry_tests',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('related_course_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['related_course_id'], ['courses.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create entry_test_questions table
    op.create_table('entry_test_questions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('entry_test_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('audio_url', sa.String(length=500), nullable=True),
        sa.Column('image_url', sa.String(length=500), nullable=True),
        sa.Column('correct_answer', sa.Text(), nullable=False),
        sa.Column('explanation', sa.Text(), nullable=True),
        sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['entry_test_id'], ['entry_tests.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create entry_test_question_options table
    op.create_table('entry_test_question_options',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('option_text', sa.Text(), nullable=False),
        sa.Column('is_correct', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['question_id'], ['entry_test_questions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create user_entry_test_results table
    op.create_table('user_entry_test_results',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('entry_test_id', sa.Integer(), nullable=False),
        sa.Column('score', sa.Float(), nullable=False),
        sa.Column('recommended_course_id', sa.Integer(), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['entry_test_id'], ['entry_tests.id'], ),
        sa.ForeignKeyConstraint(['recommended_course_id'], ['courses.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Update user_course_progress table to add started_at field
    op.add_column('user_course_progress', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove started_at column from user_course_progress
    op.drop_column('user_course_progress', 'started_at')
    
    # Drop entry test related tables
    op.drop_table('user_entry_test_results')
    op.drop_table('entry_test_question_options')
    op.drop_table('entry_test_questions')
    op.drop_table('entry_tests')
    
    # Remove foreign key constraint and columns from users table
    op.drop_constraint('fk_users_current_course_id', 'users', type_='foreignkey')
    op.drop_column('users', 'has_completed_entry_test')
    op.drop_column('users', 'entry_test_score')
    op.drop_column('users', 'current_course_id')
    
    # ### end Alembic commands ###
