"""black list

Revision ID: cff85dfb8f54
Revises: 60ce6fc2071c
Create Date: 2025-10-18 09:32:49.437833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cff85dfb8f54'
down_revision: Union[str, None] = '60ce6fc2071c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    if inspector.has_table('token_blacklist'):
        existing_indexes = {
            index['name']
            for index in inspector.get_indexes('token_blacklist')
        }

        if 'ix_token_blacklist_token' in existing_indexes:
            op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')

        op.drop_table('token_blacklist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
