"""sync models with manual DB changes

Revision ID: ec2a4594bf04
Revises: 2deb377ba4bb
Create Date: 2025-10-26 03:56:31.632342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec2a4594bf04'
down_revision: Union[str, None] = '2deb377ba4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Note: We're NOT dropping these tables because they were manually created
    # and are needed for the new schema structure
    # op.drop_table('user_final_quiz_attempts')  # COMMENTED OUT - keep this table
    # op.drop_table('exercises')  # COMMENTED OUT - keep this table
    
    # Update final_quizzes table structure
    op.alter_column('final_quizzes', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Reference to unit for final unit tests')
    op.alter_column('final_quizzes', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Type of quiz: unit_test, lesson_test, etc.',
               existing_nullable=False)
    
    # Drop old indexes and constraints if they exist
    try:
        op.drop_index(op.f('idx_quizzes_unit_id'), table_name='final_quizzes')
    except:
        pass  # Index might not exist
    
    try:
        op.drop_constraint(op.f('fk_quizzes_unit_id'), 'final_quizzes', type_='foreignkey')
    except:
        pass  # Constraint might not exist
    
    # Update questions table structure
    op.alter_column('questions', 'lesson_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to lesson for practice questions',
               existing_nullable=True)
    op.alter_column('questions', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    
    # Drop old indexes and constraints if they exist
    try:
        op.drop_index(op.f('idx_questions_lesson_id'), table_name='questions')
    except:
        pass  # Index might not exist
    
    try:
        op.drop_index(op.f('idx_questions_question_type'), table_name='questions')
    except:
        pass  # Index might not exist
    
    try:
        op.drop_constraint(op.f('fk_questions_lesson_id'), 'questions', type_='foreignkey')
    except:
        pass  # Constraint might not exist
    
    # Create new foreign key constraint
    op.create_foreign_key(None, 'questions', 'lessons', ['lesson_id'], ['id'])
    
    # Drop question_type column if it exists (it should be kept according to manual changes)
    # op.drop_column('questions', 'question_type')  # COMMENTED OUT - keep this column
    
    # Update user_question_attempts table
    try:
        op.drop_constraint(op.f('fk_user_question_attempts_lesson_id'), 'user_question_attempts', type_='foreignkey')
        op.drop_column('user_question_attempts', 'lesson_id')
    except:
        pass  # Column might not exist
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Restore user_question_attempts table
    try:
        op.add_column('user_question_attempts', sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True))
        op.create_foreign_key(op.f('fk_user_question_attempts_lesson_id'), 'user_question_attempts', 'lessons', ['lesson_id'], ['id'])
    except:
        pass  # Column might already exist
    
    # Restore questions table structure
    try:
        op.drop_constraint(None, 'questions', type_='foreignkey')
        op.create_foreign_key(op.f('fk_questions_lesson_id'), 'questions', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
        op.create_index(op.f('idx_questions_question_type'), 'questions', ['question_type'], unique=False)
        op.create_index(op.f('idx_questions_lesson_id'), 'questions', ['lesson_id'], unique=False)
        op.alter_column('questions', 'quiz_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        op.alter_column('questions', 'lesson_id',
                   existing_type=sa.INTEGER(),
                   comment='Reference to lesson for practice questions',
                   existing_nullable=True)
    except:
        pass  # Changes might not be reversible
    
    # Restore final_quizzes table structure
    try:
        op.create_foreign_key(op.f('fk_quizzes_unit_id'), 'final_quizzes', 'units', ['unit_id'], ['id'], ondelete='CASCADE')
        op.create_index(op.f('idx_quizzes_unit_id'), 'final_quizzes', ['unit_id'], unique=False)
        op.alter_column('final_quizzes', 'type',
                   existing_type=sa.VARCHAR(length=50),
                   comment='Type of quiz: unit_test, lesson_test, etc.',
                   existing_nullable=False)
        op.alter_column('final_quizzes', 'unit_id',
                   existing_type=sa.INTEGER(),
                   nullable=True,
                   comment='Reference to unit for final unit tests')
    except:
        pass  # Changes might not be reversible
    
    # Note: We're NOT recreating the dropped tables because they were manually created
    # and should be handled separately if needed
    # ### end Alembic commands ###
