"""update db

Revision ID: ef1c46c52211
Revises: 63debe8ae69d
Create Date: 2025-10-27 15:53:31.084606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1c46c52211'
down_revision: Union[str, None] = '63debe8ae69d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Thêm cột cho phép NULL tạm thời
    op.add_column('questions', sa.Column('question_type', sa.String(length=50), nullable=True))

    # 2. Gán giá trị mặc định cho các bản ghi cũ (tùy app của bạn, ví dụ 'multiple_choice')
    op.execute("UPDATE questions SET question_type = 'multiple_choice' WHERE question_type IS NULL")

    # 3. Cuối cùng, ép cột thành NOT NULL
    op.alter_column('questions', 'question_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question_type')
    # ### end Alembic commands ###
