"""update db

Revision ID: ef1c46c52211
Revises: 63debe8ae69d
Create Date: 2025-10-27 15:53:31.084606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'ef1c46c52211'
down_revision: Union[str, None] = '63debe8ae69d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    if 'questions' in inspector.get_table_names():
        columns = {col['name'] for col in inspector.get_columns('questions')}
        if 'question_type' not in columns:
            op.add_column('questions', sa.Column('question_type', sa.String(length=50), nullable=True))
            op.execute("UPDATE questions SET question_type = 'multiple_choice' WHERE question_type IS NULL")
            op.alter_column('questions', 'question_type', nullable=False)
        else:
            # ensure column is not nullable even if already existed
            op.alter_column('questions', 'question_type', existing_type=sa.String(length=50), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question_type')
    # ### end Alembic commands ###
