"""update tables

Revision ID: f86e6077e6b5
Revises: 793a9b747992
Create Date: 2025-10-06 08:25:52.606274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f86e6077e6b5'
down_revision: Union[str, None] = '793a9b747992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_constraint(op.f('fk_ai_logs_user_id'), 'ai_logs', type_='foreignkey')
    op.drop_constraint(op.f('fk_friends_friend_user_id'), 'friends', type_='foreignkey')
    op.drop_constraint(op.f('fk_friends_user_id'), 'friends', type_='foreignkey')
    op.drop_constraint(op.f('fk_leaderboard_user_id'), 'leaderboard', type_='foreignkey')
    op.drop_constraint(op.f('fk_notifications_user_id'), 'notifications', type_='foreignkey')
    op.create_unique_constraint(None, 'rate_limit', ['id'])
    op.create_unique_constraint(None, 'tier', ['id'])
    op.drop_constraint(op.f('fk_user_badges_user_id'), 'user_badges', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_challenges_user_id'), 'user_challenges', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_course_progress_user_id'), 'user_course_progress', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_exp_log_user_id'), 'user_exp_log', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_lesson_progress_user_id'), 'user_lesson_progress', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_question_errors_user_id'), 'user_question_errors', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_quiz_attempts_user_id'), 'user_quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_unit_progress_user_id'), 'user_unit_progress', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_tier'), 'users', type_='foreignkey')
    op.drop_column('users', 'tier_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_users_tier'), 'users', 'tier', ['tier_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_unit_progress_user_id'), 'user_unit_progress', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_quiz_attempts_user_id'), 'user_quiz_attempts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_question_errors_user_id'), 'user_question_errors', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_lesson_progress_user_id'), 'user_lesson_progress', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_exp_log_user_id'), 'user_exp_log', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_course_progress_user_id'), 'user_course_progress', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_challenges_user_id'), 'user_challenges', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_badges_user_id'), 'user_badges', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tier', type_='unique')
    op.drop_constraint(None, 'rate_limit', type_='unique')
    op.create_foreign_key(op.f('fk_notifications_user_id'), 'notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_leaderboard_user_id'), 'leaderboard', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_friends_user_id'), 'friends', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_friends_friend_user_id'), 'friends', 'users', ['friend_user_id'], ['id'])
    op.create_foreign_key(op.f('fk_ai_logs_user_id'), 'ai_logs', 'users', ['user_id'], ['id'])
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
